### ISSUE TITLE
TODO 20190418

### ISSUE THREAD

**Issue by karuto** [karuto/karuto-starter-theme#5]
- [ ] [Comments] Fix CSS for comment submission form.
- [ ] [Comments] Introduce JS; hide everything except the input box from the form; toggle when tapped.
- [ ] [Comments] Add "Reply to {authorName}" in the metadata field of each comment.
- [ ] [Comments] Fix CSS for edit button and "awaiting moderation" on each comment.
- [ ] [Comments] Add author badge on each comment.
